### ISSUE TITLE
Cannot Install on NC23

### ISSUE THREAD

**Issue by joeyame** [H2CK/oidc#1] opened 2022-03-20 03:25 UTC
I attempted to install this. At first was running into issues with one of the tables in my database. It was empty so I straight up removed it:
"The column 'type' on table 'oc_oidc_clients' already exists."

 Now I see the following error when I try to install:

"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes"

Not sure why this is happening - I definitely have a more recent mysql/mariadb running the database. These two errors show back and forth. If I delete the table I get error #2, and if I try again to install I get error #3

**Comment by H2CK** [comment] 2022-03-20 09:12
The issue is no installation problem with NC23 itself (as the title states). It is caused by the database type (MySQL/MariaDB) which you are using.
This initial version was only tested with SQLite and PostgreSQL. It seems that MySQL/MariaDB has some problems with the defined database structure.
A fix should be delivered soon.

**Comment by H2CK** [comment] 2022-03-20 21:48
Version 0.0.2 is now available on the App Store which should now also allow to install the app successfully when using MySQL or MariaDB.

Fixed with https://github.com/H2CK/oidc/releases/tag/0.0.2

**Closed** 2022-03-21 20:08 UTC
Labels: bug
